// Markdown export for GitHub issues / PRs.

import type { ScanReport } from "./types";
import { summarizeFindings } from "./severity";

function targetLabel(report: ScanReport): string {
  if (report.target.kind === "endpoint") return report.target.url;
  if (report.target.kind === "github") return `github:${report.target.repo}`;
  return `docker:${report.target.image}`;
}

function statusGlyph(status: string): string {
  if (status === "pass") return "✅";
  if (status === "warn") return "⚠️";
  if (status === "fail") return "❌";
  return "⏭️";
}

export function reportToMarkdown(report: ScanReport): string {
  const lines: string[] = [];
  const name = report.serverInfo?.name ?? "MCP server";
  const ver = report.serverInfo?.version ? ` v${report.serverInfo.version}` : "";

  lines.push(`# MCP Conformance Report`);
  lines.push("");
  lines.push(`**Target:** \`${targetLabel(report)}\``);
  lines.push(`**Server:** ${name}${ver}`);
  if (report.mcpVersion) lines.push(`**Protocol:** ${report.mcpVersion}`);
  lines.push(`**Scanned:** ${report.createdAt}`);
  lines.push("");
  lines.push(`## Overall`);
  lines.push("");
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Score | **${report.overall.score} / 100** |`);
  lines.push(`| Grade | **${report.overall.grade}** |`);
  lines.push(`| Security | ${report.security.score}/100 (${report.security.grade}) |`);
  lines.push(`| Enterprise readiness | ${report.enterpriseReadiness}/100 |`);
  lines.push(`| Documentation | ${report.documentationScore}/100 |`);
  const summary = summarizeFindings(report);
  lines.push(`| Critical | ${summary.critical} |`);
  lines.push(`| High | ${summary.high} |`);
  lines.push(`| Medium | ${summary.medium} |`);
  lines.push(`| Low | ${summary.low} |`);
  lines.push(`| Production ready | ${summary.productionReady ? "Yes" : "Not yet"} |`);
  lines.push("");

  if (!report.reachable) {
    lines.push(`> Scan did not complete a handshake.`);
    for (const e of report.errors) lines.push(`> ${e}`);
    lines.push("");
  }

  lines.push(`## Compatibility`);
  lines.push("");
  for (const row of report.compatibility) {
    lines.push(`- ${statusGlyph(row.status)} **${row.platform}** — ${row.note}`);
  }
  lines.push("");

  lines.push(`## Conformance breakdown`);
  lines.push("");
  for (const cat of report.categories.filter((c) => c.checks.some((k) => k.status !== "skip"))) {
    lines.push(`### ${cat.label} (${cat.score}/100)`);
    lines.push("");
    for (const c of cat.checks.filter((k) => k.status !== "skip")) {
      lines.push(`- ${statusGlyph(c.status)} **${c.label}** — ${c.detail}`);
    }
    lines.push("");
  }

  if (report.recommendations.length) {
    lines.push(`## Recommendations`);
    lines.push("");
    for (const rec of report.recommendations) {
      lines.push(`### ${rec.priority.toUpperCase()}: ${rec.issue}`);
      lines.push("");
      lines.push(`**Issue**`);
      lines.push("");
      lines.push(rec.issue);
      lines.push("");
      lines.push(`**Why it matters**`);
      lines.push("");
      lines.push(rec.why);
      lines.push("");
      lines.push(`**Suggested fix**`);
      lines.push("");
      lines.push(rec.fix);
      if (rec.reference) {
        lines.push("");
        lines.push(`**Reference**`);
        lines.push("");
        lines.push(rec.reference);
      }
      lines.push("");
    }
  }

  if (report.nextSteps.length) {
    lines.push(`## Next steps`);
    lines.push("");
    report.nextSteps.forEach((s, i) => lines.push(`${i + 1}. ${s}`));
    lines.push("");
  }

  lines.push(`---`);
  lines.push(`Generated by [ARC Labs MCP Conformance Scanner](https://mcpscanner.arctransformationgrouplab.dev) · Free · Open Source`);
  lines.push("");

  return lines.join("\n");
}
